// Gist.java
import com.google.gson.annotations.SerializedName;
import java.util.Map;

public class Gist {
    private String id;
    private String description;
    private String url;
    @SerializedName("created_at")
    private String createdAt;
    private Map<String, GistFile> files;

    // Getters and Setters (generated by IDE or manual)
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    public String getUrl() { return url; }
    public void setUrl(String url) { this.url = url; }
    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }
    public Map<String, GistFile> getFiles() { return files; }
    public void setFiles(Map<String, GistFile> files) { this.files = files; }

    @Override
    public String toString() {
        return "Gist{" +
               "id='" + id + '\'' +
               ", description='" + description + '\'' +
               ", url='" + url + '\'' +
               ", createdAt='" + createdAt + '\'' +
               ", files=" + files +
               '}';
    }
}