// GistFile.java
import com.google.gson.annotations.SerializedName;

public class GistFile {
    private String filename;
    private String type;
    private String language;
    @SerializedName("raw_url")
    private String rawUrl;
    private long size;

        // Getters and Setters (generated by IDE or manual)
public String getFilename() { return filename; }
public void setFilename(String filename) { this.filename = filename; }
public String getType() { return type; }
public void setType(String type) { this.type = type; }
public String getLanguage() { return language; }
public void setLanguage(String language) { this.language = language; }
public String getRawUrl() { return rawUrl; }
public void setRawUrl(String rawUrl) { this.rawUrl = rawUrl; }
   public long getSize() { return size; }
public void setSize(long size) { this.size = size; }

    @Override
    public String toString() {
        return "GistFile{" +
               "filename='" + filename + '\'' +
               ", type='" + type + '\'' +
               ", language='" + language + '\'' +
               ", rawUrl='" + rawUrl + '\'' +
               ", size=" + size +
               '}';
    }
}
