# helm/simple-gists-api/values.yaml

# Replica count for local development
replicaCount: 1

# Image configuration for local development
image:
  # The name of the image built directly into Minikube's image cache
  # This matches the 'docker build -t simple-gists-api:latest .' command
  repository: simple-gists-api
  tag: latest
  pullPolicy: IfNotPresent # Ensures Minikube uses its local cached image if available

# Service configuration for local development
service:
  type: NodePort # Exposes the service via a NodePort for local Minikube access
  port: 80
  targetPort: 8080 # The port your application listens on inside the container

# Resource requests and limits (can be minimal for local dev)
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Liveness and Readiness Probes (assuming /health endpoint on targetPort 8080)
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 1

# Configuration for Horizontal Pod Autoscaler (HPA) - disabled by default
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
