# helm/simple-gists-api/values.yaml
# Default values for simple-gists-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: # Placeholder, will be set by CI/CD (e.g., from ECR or Docker Hub)
  pullPolicy: IfNotPresent # AlwaysPull in production after first deploy if using immutable tags
  # Overrides the image tag whose default is the chart appVersion.
  tag: "" # Placeholder, will be set by CI/CD (e.g., GITHUB_SHA)

service:
  type: NodePort # Changed from LoadBalancer to NodePort for local Minikube access
  port: 80
  targetPort: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # decision for the user. This is just an example.
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Configuration for Horizontal Pod Autoscaler (HPA)
autoscaling:
  enabled: false # Set to true to enable HPA
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80 # Default HPA target for CPU
  # targetMemoryUtilizationPercentage: 80 # Uncomment and configure for memory-based autoscaling